# Single source of truth for UI strings. Run: python3 strings.py  -> writes Strings.tr.xaml / Strings.en.xaml
from xml.sax.saxutils import escape
S = [
 ("App_Name", "Kodiz Signage", "Kodiz Signage"),
 # Tray / global
 ("Tray_Settings", "Ayarlar", "Settings"),
 ("Tray_Start", "Gösterimi Başlat", "Start Playback"),
 ("Tray_Stop", "Gösterimi Durdur", "Stop Playback"),
 ("Tray_Next", "Sonraki Öğe", "Next Item"),
 ("Tray_Exit", "Çıkış", "Exit"),
 ("Tray_TooltipPlaying", "Kodiz Signage – gösterim açık", "Kodiz Signage – playing"),
 ("Tray_TooltipStopped", "Kodiz Signage – gösterim durduruldu", "Kodiz Signage – stopped"),
 ("Confirm_Exit", "Kodiz Signage kapatılsın mı?\nGösterim duracak.", "Exit Kodiz Signage?\nPlayback will stop."),
 # Player
 ("Player_NoContentTitle", "Gösterilecek içerik yok", "Nothing to show"),
 ("Player_NoContentHint", "Ayarlar penceresinden medya ekleyin veya öğeleri etkinleştirin.",
                          "Add media or enable items in the settings window."),
 ("Player_SettingsShortcut", "Ayarları açmak için: ", "To open settings: "),
 # Settings window
 ("Settings_Title", "Kodiz Signage – Ayarlar", "Kodiz Signage – Settings"),
 ("Status_Playing", "Gösterim açık", "Playing"),
 ("Status_Closed", "Kapalı saatler (siyah ekran)", "Closed hours (black screen)"),
 ("Status_Empty", "Gösterim açık – gösterilecek içerik yok", "Playing – nothing to show"),
 ("Status_WaitingDisplay", "Seçili ekran bekleniyor", "Waiting for the selected display"),
 ("Status_WaitingDisplayHint", "Seçili ekran bağlı değil (TV kapalı olabilir). Gösterim gizli bekliyor, ekran gelince kendiliğinden başlar.",
                               "The selected display is not connected (TV may be off). Playback is hidden and resumes by itself when it returns."),
 ("Status_Stopped", "Gösterim durduruldu", "Stopped"),
 ("Status_OnDisplay", "Ekran: {0}", "Display: {0}"),
 ("Status_Fallback", "Seçili ekran bulunamadı – geçici olarak ana ekranda gösteriliyor, 5 sn'de bir tekrar deneniyor.",
                     "Selected display not found – temporarily using the primary display, retrying every 5 s."),
 ("Action_Start", "Başlat", "Start"),
 ("Action_Stop", "Durdur", "Stop"),
 ("Action_Next", "Sonraki", "Next"),
 ("Settings_AutoSaved", "Değişiklikler otomatik kaydedilir ve gösterime anında uygulanır.",
                        "Changes are saved automatically and applied to playback instantly."),
 ("Tab_Media", "Medya", "Media"),
 ("Tab_Display", "Ekran", "Display"),
 ("Tab_General", "Genel", "General"),
 ("Tab_Shortcuts", "Kısayollar", "Shortcuts"),
 # Media tab
 ("Media_AddFiles", "Dosya Ekle", "Add Files"),
 ("Media_DropHint", "Dosyaları veya klasörleri bu pencereye sürükleyip bırakabilirsiniz", "You can drag & drop files or folders onto this window"),
 ("Media_EmptyTitle", "Henüz medya yok", "No media yet"),
 ("Media_EmptyHint", "Resim (JPG, PNG, GIF, WEBP, HEIC), video (MP4, MOV) ve PDF ekleyin", "Add images (JPG, PNG, GIF, WEBP, HEIC), videos (MP4, MOV) and PDFs"),
 ("Media_Count", "{0} öğe · {1} şu an oynatılabilir", "{0} items · {1} playable now"),
 ("Media_Col_Name", "Ad", "Name"),
 ("Media_Col_Type", "Tür", "Type"),
 ("Media_Col_Duration", "Süre (sn)", "Duration (s)"),
 ("Media_Col_Active", "Aktif", "Active"),
 ("Media_Col_Start", "Başlangıç", "Start date"),
 ("Media_Col_End", "Bitiş", "End date"),
 ("Type_Image", "Resim", "Image"),
 ("Type_Video", "Video", "Video"),
 ("Media_DefaultDuration", "Varsayılan", "Default"),
 ("Media_Auto", "otomatik", "auto"),
 ("Media_MoveUp", "Yukarı taşı", "Move up"),
 ("Media_MoveDown", "Aşağı taşı", "Move down"),
 ("Media_Delete", "Sil", "Delete"),
 ("Media_DragToReorder", "Sıralamak için sürükleyin", "Drag to reorder"),
 ("Media_Preview", "Önizleme", "Preview"),
 ("Media_NoSelection", "Ayrıntılar için listeden bir öğe seçin.\nCtrl veya Shift ile birden fazla öğe seçip hepsini birlikte düzenleyebilirsiniz.",
                       "Select an item to see its details.\nUse Ctrl or Shift to select several items and edit them together."),
 ("Media_NotPlayable", "Şu an oynatılmıyor: pasif ya da tarih, gün veya saat planının dışında.", "Not playing now: inactive or outside its dates, days or hours."),
 ("Media_CompatTooltip", "Bu dosya düzgün oynatılamayabilir, H.264 MP4 önerilir", "This file may not play correctly, H.264 MP4 is recommended"),
 ("Media_DeleteConfirm", "\"{0}\" silinsin mi?\nDosya medya klasöründen de silinecek.", "Delete \"{0}\"?\nThe file will also be removed from the media folder."),
 ("Media_Importing", "Kopyalanıyor {0}/{1}: {2}", "Copying {0}/{1}: {2}"),
 ("Media_Cancel", "İptal", "Cancel"),
 ("Media_CompatWarning", "Bu videolar düzgün oynatılamayabilir, H.264 MP4 önerilir:\n{0}\n\niPhone videoları genelde HEVC'dir. iPhone'da Ayarlar → Kamera → Formatlar → \"En Uyumlu\" seçerseniz sonraki çekimler sorunsuz oynar.",
                         "These videos may not play correctly, H.264 MP4 is recommended:\n{0}\n\niPhone videos are usually HEVC. On the iPhone choose Settings → Camera → Formats → \"Most Compatible\" for future recordings."),
 ("Media_Unsupported", "Desteklenmeyen dosyalar atlandı:\n{0}", "Unsupported files were skipped:\n{0}"),
 ("Media_ImportFailed", "Şu dosyalar eklenemedi:\n{0}", "These files could not be added:\n{0}"),
 ("Media_DateHint", "Boş bırakılırsa her gün", "Empty = every day"),
 ("Media_Details_Original", "Orijinal ad", "Original name"),
 ("Media_Details_Length", "Video süresi", "Video length"),
 ("Dialog_MediaFilter", "Medya dosyaları ve PDF", "Media files and PDF"),
 ("Dialog_AllFiles", "Tüm dosyalar", "All files"),
 # Display tab
 ("Display_Title", "Gösterim ekranı", "Output display"),
 ("Display_Description", "Gösterimin yapılacağı ekranı seçin. HDMI splitter kullanıyorsanız splitter'ın bağlı olduğu çıkışı seçin; tüm TV'ler aynı görüntüyü alır.",
                         "Choose the display used for playback. With an HDMI splitter, pick the output the splitter is connected to; all TVs show the same picture."),
 ("Display_Identify", "Ekranları Tanımla", "Identify Displays"),
 ("Display_Refresh", "Yenile", "Refresh"),
 ("Display_Primary", "Ana ekran", "Primary"),
 ("Display_Selected", "Seçili", "Selected"),
 ("Display_Use", "Bu ekranı kullan", "Use this display"),
 ("Display_Generic", "Ekran {0}", "Display {0}"),
 ("Display_None", "Hiç ekran bulunamadı.", "No displays found."),
 ("Display_SavedMissing", "Kayıtlı ekran ({0}, {1}×{2}) şu anda bağlı değil. Bağlandığında gösterim otomatik olarak oraya taşınır.",
                          "The saved display ({0}, {1}×{2}) is not connected. Playback moves there automatically when it comes back."),
 ("Display_NotConfigured", "Henüz ekran seçilmedi – ana ekran kullanılıyor.", "No display selected yet – using the primary display."),
 # General tab
 ("General_SectionPlayback", "Oynatma", "Playback"),
 ("General_SectionAppearance", "Görünüm", "Appearance"),
 ("General_SectionAudio", "Video sesi", "Video audio"),
 ("General_SectionSystem", "Sistem", "System"),
 ("General_SectionAbout", "Hakkında", "About"),
 ("General_Language", "Dil", "Language"),
 ("Language_Auto", "Sistem dili (otomatik)", "System language (automatic)"),
 ("Language_Turkish", "Türkçe", "Türkçe (Turkish)"),
 ("Language_English", "English (İngilizce)", "English"),
 ("General_StartWithWindows", "Windows açılışında otomatik başlat", "Start automatically with Windows"),
 ("General_AutoPlay", "Uygulama açılınca gösterimi otomatik başlat", "Start playback when the app launches"),
 ("General_DefaultDuration", "Resimler için varsayılan süre (saniye)", "Default image duration (seconds)"),
 ("General_Transition", "Geçiş efekti", "Transition"),
 ("Transition_None", "Yok", "None"),
 ("Transition_Fade", "Fade (yumuşak geçiş)", "Fade"),
 ("General_TransitionDuration", "Geçiş süresi", "Transition duration"),
 ("General_Scaling", "Ölçekleme", "Scaling"),
 ("Scaling_Fit", "Sığdır (kenar boşluklu)", "Fit (letterbox)"),
 ("Scaling_Fill", "Doldur (kırparak)", "Fill (crop)"),
 ("Scaling_Stretch", "Uzat", "Stretch"),
 ("General_Background", "Arka plan rengi (boş alanlar)", "Background color (letterbox areas)"),
 ("General_VideoSound", "Video sesini çal", "Play video sound"),
 ("General_Volume", "Ses seviyesi", "Volume"),
 ("General_OpenLogs", "Log klasörünü aç", "Open log folder"),
 ("General_OpenData", "Veri klasörünü aç", "Open data folder"),
 ("General_Version", "Sürüm {0}", "Version {0}"),
 # Shortcuts tab
 ("Shortcuts_Title", "Klavye kısayolları", "Keyboard shortcuts"),
 ("Shortcuts_Description",
  "Bu kısayollar Windows genelinde çalışır: gösterim tam ekrandayken ve bu pencere kapalıyken de kullanılabilir. Değiştirmek için kutuya tıklayıp yeni tuş kombinasyonuna basın.",
  "These shortcuts work system-wide: also while playback is full screen and this window is closed. To change one, click its box and press the new key combination."),
 ("Shortcuts_Rules",
  "Kısayol Ctrl, Alt veya Win tuşlarından en az birini içermelidir (F1–F24 tek başına da kullanılabilir). Kayıt sırasında diğer kısayollar geçici olarak devre dışıdır.",
  "A shortcut must include Ctrl, Alt or Win (F1–F24 may be used alone). Other shortcuts are paused while recording."),
 ("Shortcut_ShowSettings_Title", "Ayarlar penceresini aç", "Open settings"),
 ("Shortcut_ShowSettings_Description",
  "Bu pencereyi açar ve öne getirir. Gösterim tam ekranken ayarlara ulaşmanın en hızlı yolu.",
  "Opens this window and brings it to the front. The quickest way to reach the settings while playback is full screen."),
 ("Shortcut_TogglePlayback_Title", "Gösterimi durdur / başlat", "Stop / start playback"),
 ("Shortcut_TogglePlayback_Description",
  "Tam ekran gösterimi durdurur (masaüstü görünür) veya kaldığı yerden yeniden başlatır.",
  "Stops full-screen playback (the desktop becomes visible) or starts it again."),
 ("Shortcut_NextItem_Title", "Sonraki öğeye geç", "Skip to next item"),
 ("Shortcut_NextItem_Description",
  "Gösterilen resmin süresinin dolmasını veya videonun bitmesini beklemeden listedeki sonraki öğeye geçer.",
  "Moves on to the next item without waiting for the current image's duration or video to finish."),
 ("Shortcut_Exit_Title", "Uygulamadan çık", "Exit the application"),
 ("Shortcut_Exit_Description",
  "Onay sorduktan sonra uygulamayı tamamen kapatır; gösterim durur ve tray ikonu kaybolur.",
  "Asks for confirmation, then closes the application completely; playback stops and the tray icon disappears."),
 ("Shortcut_Press", "Tuş kombinasyonuna basın…", "Press a key combination…"),
 ("Shortcut_RecordHint", "Esc: iptal · Backspace: kısayolu kaldır", "Esc: cancel · Backspace: remove shortcut"),
 ("Shortcut_ClickToChange", "Değiştirmek için tıklayın", "Click to change"),
 ("Shortcut_None", "Atanmamış", "Not assigned"),
 ("Shortcut_Default", "Varsayılan: {0}", "Default: {0}"),
 ("Shortcut_Reset", "Varsayılana döndür", "Restore default"),
 ("Shortcut_Clear", "Kısayolu kaldır", "Remove shortcut"),
 ("Shortcut_ResetAll", "Tümünü varsayılana döndür", "Restore all defaults"),
 ("Shortcut_Status_Active", "Etkin", "Active"),
 ("Shortcut_Status_InUse", "Başka bir uygulama bu kombinasyonu kullanıyor, farklı bir kombinasyon seçin.",
                           "Another application uses this combination, please choose a different one."),
 ("Shortcut_Status_Invalid", "Bu kısayol kaydedilemedi.", "This shortcut could not be registered."),
 ("Shortcut_Status_Unassigned", "Kısayol yok; yalnızca tray menüsünden kullanılabilir.", "No shortcut; available from the tray menu only."),
 ("Shortcut_Error_MissingModifier", "Kısayol Ctrl, Alt veya Win tuşlarından en az birini içermeli (F1–F24 hariç).",
                                    "The shortcut must include Ctrl, Alt or Win (except F1–F24)."),
 ("Shortcut_Error_Reserved", "{0} Windows tarafından kullanılıyor, seçilemez.", "{0} is reserved by Windows and cannot be used."),
 ("Shortcut_Error_Conflict", "{0} zaten “{1}” için kullanılıyor.", "{0} is already used for “{1}”."),
 ("Shortcut_Error_Invalid", "Bu tuş kısayol olarak kullanılamaz.", "This key cannot be used as a shortcut."),
 # ---- v1.1 ----
 ("Common_Ok", "Tamam", "OK"),
 ("Common_Cancel", "İptal", "Cancel"),
 ("Preview_Button", "Önizle", "Preview"),
 ("Preview_Title", "Kodiz Signage – Önizleme (sessiz)", "Kodiz Signage – Preview (muted)"),
 ("Preview_Tooltip", "Gösterimi bu bilgisayarda küçük bir pencerede oynatır; TV'deki gösterimi etkilemez.",
                     "Plays the show in a small window on this PC; does not affect the TV."),
 ("NowPlaying_Item", "Şu an: {0}", "Now: {0}"),
 ("NowPlaying_Remaining", "Şu an: {0} · {1} sn kaldı", "Now: {0} · {1} s left"),
 ("NowPlaying_Closed", "Çalışma saatleri dışında", "Outside opening hours"),
 ("NowPlaying_Empty", "Oynatılabilir öğe yok", "No playable item"),
 ("NowPlaying_WaitingDisplay", "Ekran bekleniyor", "Waiting for display"),
 ("Media_OnAir", "YAYINDA", "ON AIR"),
 ("Media_Col_Schedule", "Plan", "Schedule"),
 ("Media_Details_Name", "Görünen ad", "Display name"),
 ("Media_Synced", "Klasörden", "From folder"),
 ("Media_SyncedTooltip", "İzlenen klasörden otomatik eklendi. Dosya klasörden silinirse buradan da kalkar.",
                         "Added automatically from the watched folder. Removed here when the file is deleted there."),
 ("Media_DeletedOne", "\"{0}\" silindi", "\"{0}\" deleted"),
 ("Media_DeletedMany", "{0} öğe silindi", "{0} items deleted"),
 ("Media_Undo", "Geri al", "Undo"),
 ("Media_Disk", "Medya {0} · Diskte {1} boş", "Media {0} · {1} free"),
 ("Media_DiskLow", "Medya {0} · Disk dolmak üzere: {1} boş", "Media {0} · Disk almost full: {1} free"),
 ("Media_DiskUsedOnly", "Medya {0}", "Media {0}"),
 ("Media_DiskFull", "Diskte yeterli boş alan olmadığı için eklenmedi:\n{0}", "Not added – not enough free disk space:\n{0}"),
 ("Media_Duplicates", "Bu dosyalar listede zaten olduğu için tekrar eklenmedi:\n{0}", "Already in the list, not added again:\n{0}"),
 ("Media_HighResWarning", "Bu videolar 1080p'den büyük (ör. 4K). Düşük güçlü bilgisayarlarda takılabilir; 1080p'ye dönüştürmeniz önerilir:\n{0}",
                          "These videos are larger than 1080p (e.g. 4K) and may stutter on low-power PCs; converting to 1080p is recommended:\n{0}"),
 ("Media_ImageCodecWarning", "Bu resimler bu bilgisayarda açılamıyor. HEIC için Microsoft Store'dan \"HEIF Görüntü Uzantıları\", WEBP için \"Webp Görüntü Uzantıları\" yükleyin ya da JPG'ye dönüştürün:\n{0}",
                             "These images cannot be opened on this PC. Install \"HEIF Image Extensions\" (HEIC) or \"Webp Image Extensions\" from the Microsoft Store, or convert them to JPG:\n{0}"),
 ("Bulk_Title", "{0} öğe seçildi", "{0} items selected"),
 ("Bulk_Hint", "Aşağıdaki değişiklikler seçili tüm öğelere uygulanır.", "The changes below apply to all selected items."),
 ("Bulk_Activate", "Hepsini aktif yap", "Activate all"),
 ("Bulk_Deactivate", "Hepsini pasif yap", "Deactivate all"),
 ("Bulk_Duration", "Resim süresi (sn, boş = varsayılan)", "Image duration (s, empty = default)"),
 ("Bulk_Apply", "Uygula", "Apply"),
 ("Bulk_Delete", "Seçilenleri sil", "Delete selected"),
 ("Schedule_Title", "Gün ve saat planı", "Days and hours"),
 ("Schedule_DatesTitle", "Tarih aralığı", "Date range"),
 ("Schedule_DatesHint", "Öğe yalnızca bu günler arasında gösterilir (iki gün de dahil). Boş bırakılırsa sınır yok.",
                        "Shown only between these days (both included). Leave empty for no limit."),
 ("Schedule_TimeHint", "Saat örn. 07:00 – 11:00. Boş = tüm gün. Bitiş başlangıçtan önceyse gece yarısını geçer (22:00 – 02:00).",
                       "Time e.g. 07:00 – 11:00. Empty = all day. An end before the start runs past midnight (22:00 – 02:00)."),
 ("Schedule_EveryDay", "Her gün", "Every day"),
 ("Schedule_Weekdays", "Hafta içi", "Weekdays"),
 ("Schedule_Weekend", "Hafta sonu", "Weekend"),
 ("Schedule_AllDay", "Tüm gün", "All day"),
 ("Schedule_Always", "Her zaman", "Always"),
 ("Schedule_InvalidTime", "Saat anlaşılamadı. Örn. 07:00 veya 7.30 yazın.", "Time not understood. Type e.g. 07:00 or 7.30."),
 ("Schedule_NoDays", "Hiç gün seçili değil; öğe hiç gösterilmez.", "No day selected; the item will never be shown."),
 ("Schedule_NoDaysShort", "Hiçbir gün", "No days"),
 ("Day_Mon", "Pzt", "Mon"),
 ("Day_Tue", "Sal", "Tue"),
 ("Day_Wed", "Çar", "Wed"),
 ("Day_Thu", "Per", "Thu"),
 ("Day_Fri", "Cum", "Fri"),
 ("Day_Sat", "Cmt", "Sat"),
 ("Day_Sun", "Paz", "Sun"),
 ("Fallback_Title", "Seçili ekran bulunamazsa", "If the selected display is missing"),
 ("Fallback_Description", "TV kapatıldığında veya splitter geç tanındığında Windows ekranı kaybedebilir. \"Gizle ve bekle\" seçiliyken gösterim başka bir ekranı (ör. kasa monitörünü) kaplamaz; ekran geri gelince kendiliğinden devam eder.",
                          "When a TV is switched off or the splitter is detected late, Windows may lose the display. With \"Hide and wait\" the show never covers another screen (e.g. the cashier monitor) and resumes by itself when the display returns."),
 ("Fallback_Hide", "Gizle ve bekle (önerilen)", "Hide and wait (recommended)"),
 ("Fallback_Primary", "Geçici olarak ana ekranda göster", "Show on the primary display meanwhile"),
 ("Hours_Title", "Çalışma saatleri", "Opening hours"),
 ("Hours_Description", "Bu saatlerin dışında TV'de siyah ekran gösterilir, içerik oynatılmaz.", "Outside these hours the TV shows a black screen and nothing is played."),
 ("Hours_Enabled", "Çalışma saatlerini kullan", "Use opening hours"),
 ("Hours_AllowDisplaySleep", "Kapalıyken ekranın uykuya geçmesine izin ver (Windows güç ayarlarına göre)", "Let the display sleep while closed (per Windows power settings)"),
 ("Folder_Title", "İzlenen klasör", "Watched folder"),
 ("Folder_Description", "Seçtiğiniz klasördeki (USB bellek, OneDrive, ağ klasörü…) dosyalar otomatik eklenir. Değişen dosyalar güncellenir; klasörden silinenler listeden de kalkar. Klasöre ulaşılamazsa (USB çıkarıldı) hiçbir şey silinmez.",
                        "Files in the chosen folder (USB stick, OneDrive, network share…) are added automatically. Changed files are updated, files deleted there are removed here. If the folder is unreachable (USB unplugged) nothing is removed."),
 ("Folder_Enabled", "Klasörü izle", "Watch the folder"),
 ("Folder_Choose", "Klasör seç", "Choose folder"),
 ("Folder_SyncNow", "Şimdi eşitle", "Sync now"),
 ("Folder_Status", "{0} · son eşitleme {1}", "{0} · last sync {1}"),
 ("Folder_Pending", "{0} · eşitleniyor…", "{0} · syncing…"),
 ("Folder_Unavailable", "{0} şu an erişilemiyor", "{0} is not reachable"),
 ("Folder_Error", "Klasör eşitleme hatası: {0}", "Folder sync error: {0}"),
 ("Folder_NotDataFolder", "Uygulamanın kendi veri klasörü seçilemez.", "The application's own data folder cannot be used."),
 ("Startup_Blocked", "Windows Görev Yöneticisi'nde başlangıçta devre dışı bırakılmış; bilgisayar açılınca başlamayacak.",
                     "Disabled in Task Manager → Startup apps; it will not start with Windows."),
 ("Startup_Fix", "Yeniden etkinleştir", "Enable again"),
 ("Pin_Section", "Güvenlik", "Security"),
 ("Pin_Description", "PIN belirlerseniz ayarları açmak, gösterimi durdurmak ve uygulamadan çıkmak için PIN sorulur. PIN'i unutursanız settings.json dosyasındaki \"pinHash\" satırını silin.",
                     "With a PIN, opening the settings, stopping playback and exiting ask for it. If you forget it, delete the \"pinHash\" line in settings.json."),
 ("Pin_On", "PIN koruması açık", "PIN protection is on"),
 ("Pin_Off", "PIN koruması kapalı", "PIN protection is off"),
 ("Pin_Set", "PIN belirle", "Set PIN"),
 ("Pin_Change", "PIN'i değiştir", "Change PIN"),
 ("Pin_Remove", "PIN'i kaldır", "Remove PIN"),
 ("Pin_RemoveConfirm", "PIN koruması kaldırılsın mı?", "Remove the PIN protection?"),
 ("Pin_Title", "PIN", "PIN"),
 ("Pin_Enter", "Devam etmek için PIN girin", "Enter the PIN to continue"),
 ("Pin_New", "Yeni PIN (4–12 rakam), iki kez", "New PIN (4–12 digits), twice"),
 ("Pin_Wrong", "PIN yanlış.", "Wrong PIN."),
 ("Pin_Invalid", "PIN 4–12 rakamdan oluşmalı.", "The PIN must be 4–12 digits."),
 ("Pin_Mismatch", "İki PIN aynı değil.", "The PINs do not match."),
 ("Pin_LockedOut", "Çok fazla yanlış deneme. {0} saniye sonra tekrar deneyin.", "Too many wrong attempts. Try again in {0} seconds."),
 ("Backup_Section", "Yedekleme", "Backup"),
 ("Backup_Description", "Ayarlar, oynatma listesi ve tüm medya tek bir .zip dosyasına yedeklenir. Yeni bir bilgisayara geçerken veya bir sorun sonrası geri yüklemek için kullanın.",
                        "Settings, playlist and all media are saved into one .zip file – for moving to a new PC or recovering after a problem."),
 ("Backup_Create", "Yedek al", "Create backup"),
 ("Backup_Restore", "Yedekten geri yükle", "Restore backup"),
 ("Backup_FileType", "Kodiz Signage yedeği", "Kodiz Signage backup"),
 ("Backup_Creating", "Yedek alınıyor…", "Creating backup…"),
 ("Backup_Restoring", "Geri yükleniyor…", "Restoring…"),
 ("Backup_Created", "Yedek kaydedildi:\n{0}", "Backup saved:\n{0}"),
 ("Backup_RestoreConfirm", "Mevcut ayarlar, liste ve medya yedektekilerle değiştirilecek. Devam edilsin mi?",
                           "Current settings, playlist and media will be replaced by the backup. Continue?"),
 ("Backup_Restored", "Yedek geri yüklendi. Uygulama yeniden başlatılacak.", "Backup restored. The application will restart."),
 ("Backup_Invalid", "Bu dosya bir Kodiz Signage yedeği değil.", "This file is not a Kodiz Signage backup."),
 ("Backup_Failed", "İşlem başarısız oldu: {0}", "The operation failed: {0}"),
 ("About_DataFolder", "Veri klasörü", "Data folder"),
 ("About_ExePath", "Uygulama konumu", "Application location"),
 ("Install_Prompt", "Kodiz Signage bilgisayara kurulsun mu? (Önerilir)\n\nUygulama kalıcı bir klasöre kopyalanır ve Başlat menüsüne eklenir. Böylece İndirilenler klasörü temizlense bile Windows açılışında başlamaya devam eder. Yönetici izni gerekmez.",
                    "Install Kodiz Signage on this PC? (Recommended)\n\nThe app is copied to a permanent folder and added to the Start menu, so it keeps starting with Windows even if the Downloads folder is cleaned. No administrator rights needed."),
 ("Update_Prompt", "Bilgisayarda Kodiz Signage {0} kurulu. Bu dosya {1} sürümü (veya aynı sürümün daha yeni bir derlemesi).\n\nKurulu sürüm bu dosyayla güncellensin mi? Ayarlarınız ve medyalarınız korunur.",
                   "Kodiz Signage {0} is installed. This file is version {1} (or a newer build of the same version).\n\nUpdate the installed copy with this file? Your settings and media are kept."),
 ("Install_Failed", "Kurulum yapılamadı. Ayrıntılar log dosyasında.", "Installation failed. See the log file for details."),
 ("Install_Done", "Kurulum tamamlandı. Uygulama kurulu konumdan yeniden açılacak.", "Installation complete. The app restarts from its installed location."),
 ("Install_NotInstalled", "Uygulama kurulu değil; bu konumdan çalışıyor. Dosya taşınır veya silinirse Windows açılışında başlamaz.",
                          "The app is not installed and runs from this location. If the file is moved or deleted it will not start with Windows."),
 ("Install_Button", "Bilgisayara kur", "Install on this PC"),
 ("TrayHint_Title", "Kodiz Signage çalışmaya devam ediyor", "Kodiz Signage keeps running"),
 ("TrayHint_Text", "Ayarlar penceresi kapatıldı, gösterim sürüyor. Tekrar açmak için {0} veya Başlat menüsündeki Kodiz Signage.",
                   "The settings window was closed; playback continues. Reopen with {0} or Kodiz Signage in the Start menu."),
 ("SafeMode_Text", "Uygulama kısa sürede birkaç kez beklenmedik şekilde kapandı. Gösterim {0} dakika sonra otomatik başlayacak. Ayrıntılar için log klasörüne bakın.",
                   "The app closed unexpectedly several times in a short period. Playback starts automatically in {0} minutes. See the log folder for details."),
 ("General_InvalidColor", "Geçersiz renk. #RRGGBB biçiminde girin.", "Invalid color. Use #RRGGBB."),
]
def write(path, idx, lang):
    keys=set()
    out=['<!-- Generated by strings.py – edit that file, not this one. -->',
         '<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"',
         '                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"',
         '                    xmlns:sys="clr-namespace:System;assembly=mscorlib">']
    for row in S:
        assert row[0] not in keys, row[0]; keys.add(row[0])
        val=escape(row[idx], {'"':'&quot;'}).replace('\n','&#10;')
        out.append(f'    <sys:String x:Key="{row[0]}" xml:space="preserve">{val}</sys:String>')
    out.append('</ResourceDictionary>\n')
    open(path,'w',encoding='utf-8').write('\n'.join(out))
import os
d=os.path.dirname(os.path.abspath(__file__))
write(os.path.join(d,'Strings.tr.xaml'),1,'tr')
write(os.path.join(d,'Strings.en.xaml'),2,'en')
