# Single source of truth for UI strings. Run: python3 strings.py  -> writes Strings.tr.xaml / Strings.en.xaml
from xml.sax.saxutils import escape
S = [
 ("App_Name", "Kodiz Signage", "Kodiz Signage"),
 # Tray / global
 ("Tray_Settings", "Ayarlar", "Settings"),
 ("Tray_Start", "Gösterimi Başlat", "Start Playback"),
 ("Tray_Stop", "Gösterimi Durdur", "Stop Playback"),
 ("Tray_Next", "Sonraki Öğe", "Next Item"),
 ("Tray_Exit", "Çıkış", "Exit"),
 ("Tray_TooltipPlaying", "Kodiz Signage – gösterim açık", "Kodiz Signage – playing"),
 ("Tray_TooltipStopped", "Kodiz Signage – gösterim durduruldu", "Kodiz Signage – stopped"),
 ("Confirm_Exit", "Kodiz Signage kapatılsın mı?\nGösterim duracak.", "Exit Kodiz Signage?\nPlayback will stop."),
 # Player
 ("Player_NoContentTitle", "Gösterilecek içerik yok", "Nothing to show"),
 ("Player_NoContentHint", "Ayarlar penceresinden medya ekleyin veya öğeleri etkinleştirin.",
                          "Add media or enable items in the settings window."),
 ("Player_SettingsShortcut", "Ayarları açmak için: ", "To open settings: "),
 # Settings window
 ("Settings_Title", "Kodiz Signage – Ayarlar", "Kodiz Signage – Settings"),
 ("Status_Playing", "Gösterim açık", "Playing"),
 ("Status_Closed", "Kapalı saatler (siyah ekran)", "Closed hours (black screen)"),
 ("Status_Empty", "Gösterim açık – gösterilecek içerik yok", "Playing – nothing to show"),
 ("Status_WaitingDisplay", "Seçili ekran bekleniyor", "Waiting for the selected display"),
 ("Status_WaitingDisplayHint", "Seçili ekran bağlı değil (TV kapalı olabilir). Gösterim gizli bekliyor, ekran gelince kendiliğinden başlar.",
                               "The selected display is not connected (TV may be off). Playback is hidden and resumes by itself when it returns."),
 ("Status_Stopped", "Gösterim durduruldu", "Stopped"),
 ("Status_OnDisplay", "Ekran: {0}", "Display: {0}"),
 ("Status_Fallback", "Seçili ekran bulunamadı – geçici olarak ana ekranda gösteriliyor, 5 sn'de bir tekrar deneniyor.",
                     "Selected display not found – temporarily using the primary display, retrying every 5 s."),
 ("Action_Start", "Başlat", "Start"),
 ("Action_Stop", "Durdur", "Stop"),
 ("Action_Next", "Sonraki", "Next"),
 ("Settings_AutoSaved", "Değişiklikler otomatik kaydedilir ve gösterime anında uygulanır.",
                        "Changes are saved automatically and applied to playback instantly."),
 ("Tab_Media", "Medya", "Media"),
 ("Tab_Display", "Ekranlar", "Screens"),
 ("Tab_General", "Genel", "General"),
 ("Tab_Shortcuts", "Kısayollar", "Shortcuts"),
 # Media tab
 ("Media_AddFiles", "Dosya Ekle", "Add Files"),
 ("Media_DropHint", "Dosyaları veya klasörleri bu pencereye sürükleyip bırakabilirsiniz", "You can drag & drop files or folders onto this window"),
 ("Media_EmptyTitle", "Henüz medya yok", "No media yet"),
 ("Media_EmptyHint", "Resim (JPG, PNG, GIF, WEBP, HEIC, AVIF, TIFF), video (MP4, MOV, MKV…), PDF ve sunum (PPTX, ODP) ekleyin – ya da kendi slaytınızı oluşturun", "Add images (JPG, PNG, GIF, WEBP, HEIC, AVIF, TIFF), videos (MP4, MOV, MKV…), PDFs and presentations (PPTX, ODP) – or create your own slide"),
 ("Media_Count", "{0} öğe · {1} şu an oynatılabilir", "{0} items · {1} playable now"),
 ("Media_Col_Name", "Ad", "Name"),
 ("Media_Col_Type", "Tür", "Type"),
 ("Media_Col_Duration", "Süre (sn)", "Duration (s)"),
 ("Media_Col_Active", "Aktif", "Active"),
 ("Media_Col_Start", "Başlangıç", "Start date"),
 ("Media_Col_End", "Bitiş", "End date"),
 ("Type_Image", "Resim", "Image"),
 ("Type_Video", "Video", "Video"),
 ("Media_DefaultDuration", "Varsayılan", "Default"),
 ("Media_Auto", "otomatik", "auto"),
 ("Media_MoveUp", "Yukarı taşı", "Move up"),
 ("Media_MoveDown", "Aşağı taşı", "Move down"),
 ("Media_Delete", "Sil", "Delete"),
 ("Media_DragToReorder", "Sıralamak için sürükleyin", "Drag to reorder"),
 ("Media_Preview", "Önizleme", "Preview"),
 ("Media_NoSelection", "Ayrıntılar için listeden bir öğe seçin.\nCtrl veya Shift ile birden fazla öğe seçip hepsini birlikte düzenleyebilirsiniz.",
                       "Select an item to see its details.\nUse Ctrl or Shift to select several items and edit them together."),
 ("Media_NotPlayable", "Şu an oynatılmıyor: pasif ya da tarih, gün veya saat planının dışında.", "Not playing now: inactive or outside its dates, days or hours."),
 ("Media_CompatTooltip", "Bu dosya düzgün oynatılamayabilir, H.264 MP4 önerilir", "This file may not play correctly, H.264 MP4 is recommended"),
 ("Media_DeleteConfirm", "\"{0}\" silinsin mi?\nDosya medya klasöründen de silinecek.", "Delete \"{0}\"?\nThe file will also be removed from the media folder."),
 ("Media_Importing", "Kopyalanıyor {0}/{1}: {2}", "Copying {0}/{1}: {2}"),
 ("Media_Cancel", "İptal", "Cancel"),
 ("Media_CompatWarning", "Bu videolar düzgün oynatılamayabilir, H.264 MP4 önerilir:\n{0}\n\niPhone videoları genelde HEVC'dir. iPhone'da Ayarlar → Kamera → Formatlar → \"En Uyumlu\" seçerseniz sonraki çekimler sorunsuz oynar.",
                         "These videos may not play correctly, H.264 MP4 is recommended:\n{0}\n\niPhone videos are usually HEVC. On the iPhone choose Settings → Camera → Formats → \"Most Compatible\" for future recordings."),
 ("Media_Unsupported", "Desteklenmeyen dosyalar atlandı:\n{0}", "Unsupported files were skipped:\n{0}"),
 ("Media_ImportFailed", "Şu dosyalar eklenemedi:\n{0}", "These files could not be added:\n{0}"),
 ("Media_DateHint", "Boş bırakılırsa her gün", "Empty = every day"),
 ("Media_Details_Original", "Orijinal ad", "Original name"),
 ("Media_Details_Length", "Video süresi", "Video length"),
 ("Dialog_MediaFilter", "Medya dosyaları ve PDF", "Media files and PDF"),
 ("Dialog_AllFiles", "Tüm dosyalar", "All files"),
 # Display tab
 ("Display_Title", "Gösterim ekranı", "Output display"),
 ("Display_Description", "Gösterimin yapılacağı ekranı seçin. HDMI splitter kullanıyorsanız splitter'ın bağlı olduğu çıkışı seçin; tüm TV'ler aynı görüntüyü alır.",
                         "Choose the display used for playback. With an HDMI splitter, pick the output the splitter is connected to; all TVs show the same picture."),
 ("Display_Identify", "Ekranları Tanımla", "Identify Displays"),
 ("Display_Refresh", "Yenile", "Refresh"),
 ("Display_Primary", "Ana ekran", "Primary"),
 ("Display_Selected", "Seçili", "Selected"),
 ("Display_Use", "Bu ekranı kullan", "Use this display"),
 ("Display_Generic", "Ekran {0}", "Display {0}"),
 ("Display_None", "Hiç ekran bulunamadı.", "No displays found."),
 ("Display_SavedMissing", "Kayıtlı ekran ({0}, {1}×{2}) şu anda bağlı değil. Bağlandığında gösterim otomatik olarak oraya taşınır.",
                          "The saved display ({0}, {1}×{2}) is not connected. Playback moves there automatically when it comes back."),
 ("Display_NotConfigured", "Henüz ekran seçilmedi – ana ekran kullanılıyor.", "No display selected yet – using the primary display."),
 # General tab
 ("General_SectionPlayback", "Oynatma", "Playback"),
 ("General_SectionAppearance", "Görünüm", "Appearance"),
 ("General_SectionAudio", "Video sesi", "Video audio"),
 ("General_SectionSystem", "Sistem", "System"),
 ("General_SectionAbout", "Hakkında", "About"),
 ("General_Language", "Dil", "Language"),
 ("Language_Auto", "Sistem dili (otomatik)", "System language (automatic)"),
 ("Language_Turkish", "Türkçe", "Türkçe (Turkish)"),
 ("Language_English", "English (İngilizce)", "English"),
 ("General_StartWithWindows", "Windows açılışında otomatik başlat", "Start automatically with Windows"),
 ("General_AutoPlay", "Uygulama açılınca gösterimi otomatik başlat", "Start playback when the app launches"),
 ("General_DefaultDuration", "Resimler için varsayılan süre (saniye)", "Default image duration (seconds)"),
 ("General_Transition", "Geçiş efekti", "Transition"),
 ("Transition_None", "Yok", "None"),
 ("Transition_Fade", "Fade (yumuşak geçiş)", "Fade"),
 ("General_TransitionDuration", "Geçiş süresi", "Transition duration"),
 ("General_Scaling", "Ölçekleme", "Scaling"),
 ("Scaling_Fit", "Sığdır (kenar boşluklu)", "Fit (letterbox)"),
 ("Scaling_Fill", "Doldur (kırparak)", "Fill (crop)"),
 ("Scaling_Stretch", "Uzat", "Stretch"),
 ("General_Background", "Arka plan rengi (boş alanlar)", "Background color (letterbox areas)"),
 ("General_VideoSound", "Video sesini çal", "Play video sound"),
 ("General_Volume", "Ses seviyesi", "Volume"),
 ("General_OpenLogs", "Log klasörünü aç", "Open log folder"),
 ("General_OpenData", "Veri klasörünü aç", "Open data folder"),
 ("General_Version", "Sürüm {0}", "Version {0}"),
 # Shortcuts tab
 ("Shortcuts_Title", "Klavye kısayolları", "Keyboard shortcuts"),
 ("Shortcuts_Description",
  "Bu kısayollar Windows genelinde çalışır: gösterim tam ekrandayken ve bu pencere kapalıyken de kullanılabilir. Değiştirmek için kutuya tıklayıp yeni tuş kombinasyonuna basın.",
  "These shortcuts work system-wide: also while playback is full screen and this window is closed. To change one, click its box and press the new key combination."),
 ("Shortcuts_Rules",
  "Kısayol Ctrl, Alt veya Win tuşlarından en az birini içermelidir (F1–F24 tek başına da kullanılabilir). Kayıt sırasında diğer kısayollar geçici olarak devre dışıdır.",
  "A shortcut must include Ctrl, Alt or Win (F1–F24 may be used alone). Other shortcuts are paused while recording."),
 ("Shortcut_ShowSettings_Title", "Ayarlar penceresini aç", "Open settings"),
 ("Shortcut_ShowSettings_Description",
  "Bu pencereyi açar ve öne getirir. Gösterim tam ekranken ayarlara ulaşmanın en hızlı yolu.",
  "Opens this window and brings it to the front. The quickest way to reach the settings while playback is full screen."),
 ("Shortcut_TogglePlayback_Title", "Gösterimi durdur / başlat", "Stop / start playback"),
 ("Shortcut_TogglePlayback_Description",
  "Tam ekran gösterimi durdurur (masaüstü görünür) veya kaldığı yerden yeniden başlatır.",
  "Stops full-screen playback (the desktop becomes visible) or starts it again."),
 ("Shortcut_NextItem_Title", "Sonraki öğeye geç", "Skip to next item"),
 ("Shortcut_NextItem_Description",
  "Gösterilen resmin süresinin dolmasını veya videonun bitmesini beklemeden listedeki sonraki öğeye geçer.",
  "Moves on to the next item without waiting for the current image's duration or video to finish."),
 ("Shortcut_Exit_Title", "Uygulamadan çık", "Exit the application"),
 ("Shortcut_Exit_Description",
  "Onay sorduktan sonra uygulamayı tamamen kapatır; gösterim durur ve tray ikonu kaybolur.",
  "Asks for confirmation, then closes the application completely; playback stops and the tray icon disappears."),
 ("Shortcut_Press", "Tuş kombinasyonuna basın…", "Press a key combination…"),
 ("Shortcut_RecordHint", "Esc: iptal · Backspace: kısayolu kaldır", "Esc: cancel · Backspace: remove shortcut"),
 ("Shortcut_ClickToChange", "Değiştirmek için tıklayın", "Click to change"),
 ("Shortcut_None", "Atanmamış", "Not assigned"),
 ("Shortcut_Default", "Varsayılan: {0}", "Default: {0}"),
 ("Shortcut_Reset", "Varsayılana döndür", "Restore default"),
 ("Shortcut_Clear", "Kısayolu kaldır", "Remove shortcut"),
 ("Shortcut_ResetAll", "Tümünü varsayılana döndür", "Restore all defaults"),
 ("Shortcut_Status_Active", "Etkin", "Active"),
 ("Shortcut_Status_InUse", "Başka bir uygulama bu kombinasyonu kullanıyor, farklı bir kombinasyon seçin.",
                           "Another application uses this combination, please choose a different one."),
 ("Shortcut_Status_Invalid", "Bu kısayol kaydedilemedi.", "This shortcut could not be registered."),
 ("Shortcut_Status_Unassigned", "Kısayol yok; yalnızca tray menüsünden kullanılabilir.", "No shortcut; available from the tray menu only."),
 ("Shortcut_Error_MissingModifier", "Kısayol Ctrl, Alt veya Win tuşlarından en az birini içermeli (F1–F24 hariç).",
                                    "The shortcut must include Ctrl, Alt or Win (except F1–F24)."),
 ("Shortcut_Error_Reserved", "{0} Windows tarafından kullanılıyor, seçilemez.", "{0} is reserved by Windows and cannot be used."),
 ("Shortcut_Error_Conflict", "{0} zaten “{1}” için kullanılıyor.", "{0} is already used for “{1}”."),
 ("Shortcut_Error_Invalid", "Bu tuş kısayol olarak kullanılamaz.", "This key cannot be used as a shortcut."),
 # ---- v1.1 ----
 ("Common_Ok", "Tamam", "OK"),
 ("Common_Cancel", "İptal", "Cancel"),
 ("Common_Yes", "Evet", "Yes"),
 ("Common_No", "Hayır", "No"),
 ("Preview_Button", "Önizle", "Preview"),
 ("Preview_Title", "Kodiz Signage – Önizleme (sessiz)", "Kodiz Signage – Preview (muted)"),
 ("Preview_Tooltip", "Gösterimi bu bilgisayarda küçük bir pencerede oynatır; TV'deki gösterimi etkilemez.",
                     "Plays the show in a small window on this PC; does not affect the TV."),
 ("NowPlaying_Item", "Şu an: {0}", "Now: {0}"),
 ("NowPlaying_Remaining", "Şu an: {0} · {1} sn kaldı", "Now: {0} · {1} s left"),
 ("NowPlaying_Closed", "Çalışma saatleri dışında", "Outside opening hours"),
 ("NowPlaying_Empty", "Oynatılabilir öğe yok", "No playable item"),
 ("NowPlaying_WaitingDisplay", "Ekran bekleniyor", "Waiting for display"),
 ("Media_OnAir", "YAYINDA", "ON AIR"),
 ("Media_Col_Schedule", "Plan", "Schedule"),
 ("Media_Details_Name", "Görünen ad", "Display name"),
 ("Media_Synced", "Klasörden", "From folder"),
 ("Media_SyncedTooltip", "İzlenen klasörden otomatik eklendi. Dosya klasörden silinirse buradan da kalkar.",
                         "Added automatically from the watched folder. Removed here when the file is deleted there."),
 ("Media_DeletedOne", "\"{0}\" silindi", "\"{0}\" deleted"),
 ("Media_DeletedMany", "{0} öğe silindi", "{0} items deleted"),
 ("Media_Undo", "Geri al", "Undo"),
 ("Media_Disk", "Medya {0} · Diskte {1} boş", "Media {0} · {1} free"),
 ("Media_DiskLow", "Medya {0} · Disk dolmak üzere: {1} boş", "Media {0} · Disk almost full: {1} free"),
 ("Media_DiskUsedOnly", "Medya {0}", "Media {0}"),
 ("Media_DiskFull", "Diskte yeterli boş alan olmadığı için eklenmedi:\n{0}", "Not added – not enough free disk space:\n{0}"),
 ("Media_Duplicates", "Bu dosyalar listede zaten olduğu için tekrar eklenmedi:\n{0}", "Already in the list, not added again:\n{0}"),
 ("Media_HighResWarning", "Bu videolar 1080p'den büyük (ör. 4K). Düşük güçlü bilgisayarlarda takılabilir; 1080p'ye dönüştürmeniz önerilir:\n{0}",
                          "These videos are larger than 1080p (e.g. 4K) and may stutter on low-power PCs; converting to 1080p is recommended:\n{0}"),
 ("Media_ImageCodecWarning", "Bu resimler bu bilgisayarda açılamıyor. HEIC için Microsoft Store'dan \"HEIF Görüntü Uzantıları\", WEBP için \"Webp Görüntü Uzantıları\" yükleyin ya da JPG'ye dönüştürün:\n{0}",
                             "These images cannot be opened on this PC. Install \"HEIF Image Extensions\" (HEIC) or \"Webp Image Extensions\" from the Microsoft Store, or convert them to JPG:\n{0}"),
 ("Bulk_Title", "{0} öğe seçildi", "{0} items selected"),
 ("Bulk_Hint", "Aşağıdaki değişiklikler seçili tüm öğelere uygulanır.", "The changes below apply to all selected items."),
 ("Bulk_Activate", "Hepsini aktif yap", "Activate all"),
 ("Bulk_Deactivate", "Hepsini pasif yap", "Deactivate all"),
 ("Bulk_Duration", "Resim süresi (sn, boş = varsayılan)", "Image duration (s, empty = default)"),
 ("Bulk_Apply", "Uygula", "Apply"),
 ("Bulk_Delete", "Seçilenleri sil", "Delete selected"),
 ("Schedule_Title", "Gün ve saat planı", "Days and hours"),
 ("Schedule_DatesTitle", "Tarih aralığı", "Date range"),
 ("Schedule_DatesHint", "Öğe yalnızca bu günler arasında gösterilir (iki gün de dahil). Boş bırakılırsa sınır yok.",
                        "Shown only between these days (both included). Leave empty for no limit."),
 ("Schedule_TimeHint", "Saat örn. 07:00 – 11:00. Boş = tüm gün. Bitiş başlangıçtan önceyse gece yarısını geçer (22:00 – 02:00).",
                       "Time e.g. 07:00 – 11:00. Empty = all day. An end before the start runs past midnight (22:00 – 02:00)."),
 ("Schedule_EveryDay", "Her gün", "Every day"),
 ("Schedule_Weekdays", "Hafta içi", "Weekdays"),
 ("Schedule_Weekend", "Hafta sonu", "Weekend"),
 ("Schedule_AllDay", "Tüm gün", "All day"),
 ("Schedule_Always", "Her zaman", "Always"),
 ("Schedule_InvalidTime", "Saat anlaşılamadı. Örn. 07:00 veya 7.30 yazın.", "Time not understood. Type e.g. 07:00 or 7.30."),
 ("Schedule_NoDays", "Hiç gün seçili değil; öğe hiç gösterilmez.", "No day selected; the item will never be shown."),
 ("Schedule_NoDaysShort", "Hiçbir gün", "No days"),
 ("Day_Mon", "Pzt", "Mon"),
 ("Day_Tue", "Sal", "Tue"),
 ("Day_Wed", "Çar", "Wed"),
 ("Day_Thu", "Per", "Thu"),
 ("Day_Fri", "Cum", "Fri"),
 ("Day_Sat", "Cmt", "Sat"),
 ("Day_Sun", "Paz", "Sun"),
 ("Fallback_Title", "Seçili ekran bulunamazsa", "If the selected display is missing"),
 ("Fallback_Description", "TV kapatıldığında veya splitter geç tanındığında Windows ekranı kaybedebilir. \"Gizle ve bekle\" seçiliyken gösterim başka bir ekranı (ör. kasa monitörünü) kaplamaz; ekran geri gelince kendiliğinden devam eder.",
                          "When a TV is switched off or the splitter is detected late, Windows may lose the display. With \"Hide and wait\" the show never covers another screen (e.g. the cashier monitor) and resumes by itself when the display returns."),
 ("Fallback_Hide", "Gizle ve bekle (önerilen)", "Hide and wait (recommended)"),
 ("Fallback_Primary", "Geçici olarak ana ekranda göster", "Show on the primary display meanwhile"),
 ("Hours_Title", "Çalışma saatleri", "Opening hours"),
 ("Hours_Description", "Bu saatlerin dışında TV'de siyah ekran gösterilir, içerik oynatılmaz.", "Outside these hours the TV shows a black screen and nothing is played."),
 ("Hours_Enabled", "Çalışma saatlerini kullan", "Use opening hours"),
 ("Hours_AllowDisplaySleep", "Kapalıyken ekranın uykuya geçmesine izin ver (Windows güç ayarlarına göre)", "Let the display sleep while closed (per Windows power settings)"),
 ("Folder_Title", "İzlenen klasör", "Watched folder"),
 ("Folder_Description", "Seçtiğiniz klasördeki (USB bellek, OneDrive, ağ klasörü…) dosyalar otomatik eklenir. Değişen dosyalar güncellenir; klasörden silinenler listeden de kalkar. Klasöre ulaşılamazsa (USB çıkarıldı) hiçbir şey silinmez.",
                        "Files in the chosen folder (USB stick, OneDrive, network share…) are added automatically. Changed files are updated, files deleted there are removed here. If the folder is unreachable (USB unplugged) nothing is removed."),
 ("Folder_Enabled", "Klasörü izle", "Watch the folder"),
 ("Folder_Choose", "Klasör seç", "Choose folder"),
 ("Folder_SyncNow", "Şimdi eşitle", "Sync now"),
 ("Folder_Status", "{0} · son eşitleme {1}", "{0} · last sync {1}"),
 ("Folder_Pending", "{0} · eşitleniyor…", "{0} · syncing…"),
 ("Folder_Unavailable", "{0} şu an erişilemiyor", "{0} is not reachable"),
 ("Folder_Error", "Klasör eşitleme hatası: {0}", "Folder sync error: {0}"),
 ("Folder_NotDataFolder", "Uygulamanın kendi veri klasörü seçilemez.", "The application's own data folder cannot be used."),
 ("Startup_Blocked", "Windows Görev Yöneticisi'nde başlangıçta devre dışı bırakılmış; bilgisayar açılınca başlamayacak.",
                     "Disabled in Task Manager → Startup apps; it will not start with Windows."),
 ("Startup_Fix", "Yeniden etkinleştir", "Enable again"),
 ("Pin_Section", "Güvenlik", "Security"),
 ("Pin_Description", "PIN belirlerseniz ayarları açmak, gösterimi durdurmak ve uygulamadan çıkmak için PIN sorulur. PIN'i unutursanız settings.json dosyasındaki \"pinHash\" satırını silin.",
                     "With a PIN, opening the settings, stopping playback and exiting ask for it. If you forget it, delete the \"pinHash\" line in settings.json."),
 ("Pin_On", "PIN koruması açık", "PIN protection is on"),
 ("Pin_Off", "PIN koruması kapalı", "PIN protection is off"),
 ("Pin_Set", "PIN belirle", "Set PIN"),
 ("Pin_Change", "PIN'i değiştir", "Change PIN"),
 ("Pin_Remove", "PIN'i kaldır", "Remove PIN"),
 ("Pin_RemoveConfirm", "PIN koruması kaldırılsın mı?", "Remove the PIN protection?"),
 ("Pin_Title", "PIN", "PIN"),
 ("Pin_Enter", "Devam etmek için PIN girin", "Enter the PIN to continue"),
 ("Pin_New", "Yeni PIN (4–12 rakam), iki kez", "New PIN (4–12 digits), twice"),
 ("Pin_Wrong", "PIN yanlış.", "Wrong PIN."),
 ("Pin_Invalid", "PIN 4–12 rakamdan oluşmalı.", "The PIN must be 4–12 digits."),
 ("Pin_Mismatch", "İki PIN aynı değil.", "The PINs do not match."),
 ("Pin_LockedOut", "Çok fazla yanlış deneme. {0} saniye sonra tekrar deneyin.", "Too many wrong attempts. Try again in {0} seconds."),
 ("Backup_Section", "Yedekleme", "Backup"),
 ("Backup_Description", "Ayarlar, oynatma listesi ve tüm medya tek bir .zip dosyasına yedeklenir. Yeni bir bilgisayara geçerken veya bir sorun sonrası geri yüklemek için kullanın.",
                        "Settings, playlist and all media are saved into one .zip file – for moving to a new PC or recovering after a problem."),
 ("Backup_Create", "Yedek al", "Create backup"),
 ("Backup_Restore", "Yedekten geri yükle", "Restore backup"),
 ("Backup_FileType", "Kodiz Signage yedeği", "Kodiz Signage backup"),
 ("Backup_Creating", "Yedek alınıyor…", "Creating backup…"),
 ("Backup_Restoring", "Geri yükleniyor…", "Restoring…"),
 ("Backup_Created", "Yedek kaydedildi:\n{0}", "Backup saved:\n{0}"),
 ("Backup_RestoreConfirm", "Mevcut ayarlar, liste ve medya yedektekilerle değiştirilecek. Devam edilsin mi?",
                           "Current settings, playlist and media will be replaced by the backup. Continue?"),
 ("Backup_Restored", "Yedek geri yüklendi. Uygulama yeniden başlatılacak.", "Backup restored. The application will restart."),
 ("Backup_Invalid", "Bu dosya bir Kodiz Signage yedeği değil.", "This file is not a Kodiz Signage backup."),
 ("Backup_Failed", "İşlem başarısız oldu: {0}", "The operation failed: {0}"),
 ("About_DataFolder", "Veri klasörü", "Data folder"),
 ("About_ExePath", "Uygulama konumu", "Application location"),
 ("Install_Prompt", "Kodiz Signage bilgisayara kurulsun mu? (Önerilir)\n\nUygulama kalıcı bir klasöre kopyalanır ve Başlat menüsüne eklenir. Böylece İndirilenler klasörü temizlense bile Windows açılışında başlamaya devam eder. Yönetici izni gerekmez.",
                    "Install Kodiz Signage on this PC? (Recommended)\n\nThe app is copied to a permanent folder and added to the Start menu, so it keeps starting with Windows even if the Downloads folder is cleaned. No administrator rights needed."),
 ("Update_Prompt", "Bilgisayarda Kodiz Signage {0} kurulu. Bu dosya {1} sürümü (veya aynı sürümün daha yeni bir derlemesi).\n\nKurulu sürüm bu dosyayla güncellensin mi? Ayarlarınız ve medyalarınız korunur.",
                   "Kodiz Signage {0} is installed. This file is version {1} (or a newer build of the same version).\n\nUpdate the installed copy with this file? Your settings and media are kept."),
 ("Install_Failed", "Kurulum yapılamadı. Ayrıntılar log dosyasında.", "Installation failed. See the log file for details."),
 ("Install_Done", "Kurulum tamamlandı. Uygulama kurulu konumdan yeniden açılacak.", "Installation complete. The app restarts from its installed location."),
 ("Install_NotInstalled", "Uygulama kurulu değil; bu konumdan çalışıyor. Dosya taşınır veya silinirse Windows açılışında başlamaz.",
                          "The app is not installed and runs from this location. If the file is moved or deleted it will not start with Windows."),
 ("Install_Button", "Bilgisayara kur", "Install on this PC"),
 ("TrayHint_Title", "Kodiz Signage çalışmaya devam ediyor", "Kodiz Signage keeps running"),
 ("TrayHint_Text", "Ayarlar penceresi kapatıldı, gösterim sürüyor. Tekrar açmak için {0} veya Başlat menüsündeki Kodiz Signage.",
                   "The settings window was closed; playback continues. Reopen with {0} or Kodiz Signage in the Start menu."),
 ("SafeMode_Text", "Uygulama kısa sürede birkaç kez beklenmedik şekilde kapandı. Gösterim {0} dakika sonra otomatik başlayacak. Ayrıntılar için log klasörüne bakın.",
                   "The app closed unexpectedly several times in a short period. Playback starts automatically in {0} minutes. See the log folder for details."),
 # ---- v1.2 multi-screen ----
 ("Screens_Title", "Ekranlar", "Screens"),
 ("Screens_Description", "Soldan bir ekran seçin: sağda yalnızca o ekranın listesi ve ayarları görünür.", "Pick a screen on the left: its own playlist and settings appear on the right."),
 ("Screens_Summary", "{0} ekran algılandı · {1} ekranda gösterim açık", "{0} displays detected · showing on {1} screens"),
 ("Screens_NoneEnabled", "Hiçbir ekranda gösterim açık değil. Ekranlar sekmesinden en az bir ekranı açın.", "No screen is enabled. Switch on at least one screen in the Screens tab."),
 ("Screen_Default", "Ekran {0}", "Screen {0}"),
 ("Screen_ShowHere", "Bu ekranda gösterim", "Show on this screen"),
 ("Screen_NotConnected", "Bağlı değil", "Not connected"),
 ("Screen_NotUsed", "Kullanılmıyor – açmak için sağdaki anahtarı kullanın", "Not used – switch it on with the toggle on the right"),
 ("Screen_Off", "kapalı", "off"),
 ("Screen_Playing", "Oynuyor: {0}", "Playing: {0}"),
 ("Screen_PlayingFallback", "Ana ekranda oynuyor (kendi ekranı yok): {0}", "Playing on the primary display (own display missing): {0}"),
 ("Screen_Empty", "Bu ekran için şu an gösterilecek medya yok", "Nothing to show on this screen right now"),
 ("Screen_Waiting", "Ekran bekleniyor – bağlanınca kendiliğinden başlar", "Waiting for the display – starts by itself when connected"),
 ("Screen_Missing", "Kayıtlı ekran: {0}, {1} × {2} – şu an bağlı değil", "Saved display: {0}, {1} × {2} – not connected"),
 ("Screen_MissingPrimary", "Ana ekranı kullanır – şu an başka bir ekran ona atanmış", "Uses the primary display – currently taken by another screen"),
 ("Screen_MediaCount", "{0} medya atanmış · {1} şu an oynatılabilir", "{0} media assigned · {1} playable now"),
 ("Screen_NameHint", "Ekrana bir isim verin (ör. Bar üstü, Kasa, Vitrin)", "Name this screen (e.g. Above the bar, Counter, Window)"),
 ("Screen_EditMedia", "Medyayı düzenle", "Edit media"),
 ("Screen_Appearance", "Görünüm", "Appearance"),
 ("Screen_Forget", "Unut", "Forget"),
 ("Screen_ForgetConfirm", "\"{0}\" unutulsun mu? Ekranın ayarları silinir; medyalar silinmez.", "Forget \"{0}\"? Its settings are removed; media is kept."),
 ("Screen_OwnBackground", "Farklı arka plan rengi", "Own background color"),
 ("ScreenOverride_General", "Genel ayarı kullan", "Use general setting"),
 ("ScreenOverride_SoundOn", "Ses açık", "Sound on"),
 ("ScreenOverride_SoundOff", "Ses kapalı", "Sound off"),
 ("Filter_Label", "Gösterilen:", "Showing:"),
 ("Filter_AllMedia", "Tüm medya", "All media"),
 ("Media_CountScreen", "{0}: {1} öğe · {2} şu an oynatılabilir", "{0}: {1} items · {2} playable now"),
 ("Media_Screens", "Gösterileceği ekranlar", "Shown on screens"),
 ("Media_AllScreens", "Tüm ekranlar (sonradan eklenenler dahil)", "All screens (including ones added later)"),
 ("Media_OnNoScreen", "hiçbir ekranda değil", "on no screen"),
 ("Media_OnNoScreenHint", "Bu öğe açık olan hiçbir ekranda gösterilmiyor.", "This item is not shown on any enabled screen."),
 ("Bulk_SetScreens", "Yalnızca işaretli ekranlar", "Only the checked screens"),
 ("Bulk_AddScreens", "İşaretlileri ekle", "Add checked"),
 ("Bulk_RemoveScreens", "İşaretlileri çıkar", "Remove checked"),
 ("NowPlaying_Screens", "{0}/{1} ekranda yayın var", "On air on {0}/{1} screens"),
 ("Status_NoScreens", "Açık ekran yok", "No screen enabled"),
 ("Status_OnScreens", "{0} ekranda gösterim", "Showing on {0} screens"),
 ("Status_PartiallyWaiting", "{0}/{1} ekran oynuyor · bekleyen ekran: {2}", "{0}/{1} screens playing · waiting: {2}"),
 # ---- v1.3 library + per-screen playlists ----
 ("Tab_Library", "Kütüphane", "Library"),
 ("Unit_Seconds", "sn", "s"),
 ("Library_Search", "Kütüphanede ara…", "Search the library…"),
 ("Library_Hint", "Her dosya bir kez saklanır; ekranlar aynı dosyayı paylaşır. Ekrana özel sıra ve ayarlar Ekranlar sekmesinde.",
                  "Every file is stored once; screens share it. Screen-specific order and settings are in the Screens tab."),
 ("Library_Count", "{0} medya", "{0} media"),
 ("Library_CountUnused", "{0} medya · {1} tanesi hiçbir ekranda kullanılmıyor", "{0} media · {1} not used on any screen"),
 ("Library_AutoAddLabel", "Yeni medya otomatik eklensin:", "Add new media automatically to:"),
 ("Library_AutoAddTo", "Yeni eklenen medya Ekran {0} listesine düşer", "New media goes to screen {0}"),
 ("Library_AutoAddNone", "Yeni medya hiçbir ekrana otomatik eklenmez – ekranlara elle ekleyin", "New media is not added to any screen automatically – add it by hand"),
 ("Library_UsedOn", "Ekran {0}", "Screen {0}"),
 ("Library_NotUsed", "Hiçbir ekranda kullanılmıyor", "Not used on any screen"),
 ("Library_ActiveTooltip", "Varsayılan olarak aktif (ekranlar kendi ayarıyla değiştirebilir)", "Active by default (screens may override)"),
 ("Library_DefaultsInfo", "Bunlar varsayılan değerlerdir. Bir ekran kendi değerini belirlemediyse bunlar kullanılır. Ekrana özel değerler Ekranlar sekmesinde ayarlanır.",
                          "These are defaults. A screen uses them unless it sets its own value in the Screens tab."),
 ("Library_DefaultActive", "Varsayılan olarak aktif", "Active by default"),
 ("Library_DefaultDuration", "Varsayılan süre (sn, boş = ekranın varsayılanı)", "Default duration (s, empty = the screen's default)"),
 ("Library_OpenScreen", "Bu ekranın listesini aç", "Open this screen's playlist"),
 ("Library_Delete", "Kütüphaneden sil (tüm ekranlardan kalkar)", "Delete from library (removed from all screens)"),
 ("Library_AlsoFromScreens", "{0} ekrandan da kaldırıldı", "also removed from {0} screens"),
 ("Library_RemovedFromScreen", "\"{0}\", {1} listesinden çıkarıldı", "\"{0}\" removed from {1}"),
 ("Picker_Title", "{0} listesine kütüphaneden ekle", "Add from library to {0}"),
 ("Picker_Search", "Ara…", "Search…"),
 ("Picker_SelectAll", "Tümünü seç", "Select all"),
 ("Picker_AlreadyThere", "bu ekranda var", "already on this screen"),
 ("Picker_Count", "{0} medya seçildi", "{0} selected"),
 ("Picker_Add", "Ekle ({0})", "Add ({0})"),
 ("Picker_LibraryEmpty", "Kütüphane boş. Önce Kütüphane sekmesinden medya ekleyin.", "The library is empty. Add media in the Library tab first."),
 ("Screens_AllTitle", "Tüm ekranlar için", "For all screens"),
 ("Screen_UnusedHint", "Bu ekranda henüz gösterim yapılmıyor. Açtığınızda boş bir oynatma listesiyle başlar; kütüphaneden medya ekleyebilir veya başka bir ekranın listesini kopyalayabilirsiniz.",
                       "This display is not used yet. Once switched on it starts with an empty playlist; add media from the library or copy another screen's playlist."),
 ("Screen_PrimaryDisplay", "Windows'un ana ekranını kullanır", "Uses the Windows primary display"),
 ("Card_Linked", "Ekran {0} listesini oynatıyor", "Plays screen {0}'s playlist"),
 ("Card_LinkedSync", "Ekran {0} ile senkron", "In sync with screen {0}"),
 ("Audio_Title", "Video sesi nereden çıksın?", "Where should video sound play?"),
 ("Audio_EachScreen", "Her ekran kendi ayarına göre", "Each screen by its own setting"),
 ("Audio_OnlyScreen", "Yalnızca {0}", "Only {0}"),
 ("Performance_Preload", "Sonraki videoyu önceden yükle (akıcı geçiş)", "Preload the next video (smooth transitions)"),
 ("Performance_PreloadHint", "Kapatılırsa her ekranda tek video çözücü çalışır; zayıf bilgisayarlarda çok ekranlı videoda takılmayı azaltır, geçişte kısa bir bekleme olabilir.",
                             "When off, each screen uses one video decoder; reduces stutter on weak PCs with many video screens, at the cost of a short pause between videos."),
 ("Performance_Warning", "{0} ekranda video var; aynı anda {1} video çözücü çalışabilir. Takılma olursa önceden yüklemeyi kapatın veya videoları 1080p'ye dönüştürün.",
                         "{0} screens play videos; up to {1} decoders may run at once. If playback stutters, turn off preloading or convert videos to 1080p."),
 ("Rotation_Title", "Döndürme", "Rotation"),
 ("Rotation_Hint", "Dikey asılmış veya ters takılmış TV'ler için. Windows ayarlarına dokunmaz.", "For TVs mounted in portrait or upside down. Does not change Windows settings."),
 ("Rotation_0", "Yok (yatay)", "None (landscape)"),
 ("Rotation_90", "90° (dikey)", "90° (portrait)"),
 ("Rotation_180", "180° (ters)", "180° (upside down)"),
 ("Rotation_270", "270° (dikey, diğer yön)", "270° (portrait, other way)"),
 ("Editor_Header", "{0} düzenleniyor – buradaki değişiklikler yalnızca bu ekranı etkiler", "Editing {0} – changes here affect only this screen"),
 ("Editor_TabPlaylist", "Oynatma listesi", "Playlist"),
 ("Editor_TabSettings", "Ekran ayarları", "Screen settings"),
 ("Editor_Summary", "{0} öğe · {1} şu an oynatılabilir", "{0} items · {1} playable now"),
 ("Editor_LinkNone", "Kendi listesini oynatır", "Plays its own playlist"),
 ("Editor_LinkTo", "{0} listesini oynatır", "Plays the playlist of {0}"),
 ("Editor_LinkHint", "Başka bir ekranın listesini oynatırsa o listedeki değişiklikler bu ekrana da yansır.", "When playing another screen's playlist, changes there apply here too."),
 ("Editor_LinkConfirm", "Bu ekran artık {0} listesini oynatacak. Kendi listesi saklanır; bağlantıyı kaldırınca geri gelir. Devam edilsin mi?",
                        "This screen will play the playlist of {0}. Its own playlist is kept and comes back when unlinked. Continue?"),
 ("Editor_Linked", "Bu ekran {0} listesini oynatıyor. Listeyi değiştirmek için o ekranı seçin veya yukarıdan \"Kendi listesini oynatır\" seçeneğine dönün.",
                   "This screen plays the playlist of {0}. Select that screen to edit it, or switch back to \"Plays its own playlist\" above."),
 ("Editor_LinkedSync", "Bu ekran {0} ile senkron oynuyor: aynı öğeye aynı anda geçer.", "This screen plays in sync with {0}: it switches items at the same moment."),
 ("Editor_Synchronized", "Senkron oynat", "Play in sync"),
 ("Editor_SynchronizedHint", "Bağlı ekranla aynı öğeyi aynı anda gösterir (yan yana TV'ler için).", "Shows the same item at the same moment as the linked screen (for TVs side by side)."),
 ("Editor_AutoAdd", "Kütüphaneye eklenen yeni medyayı bu listeye otomatik ekle", "Add new library media to this playlist automatically"),
 ("Editor_AddFromLibrary", "Kütüphaneden ekle", "Add from library"),
 ("Editor_AddFiles", "Bu ekrana dosya ekle", "Add files to this screen"),
 ("Editor_CopyFrom", "Başka ekrandan kopyala…", "Copy from another screen…"),
 ("Editor_CopyConfirm", "{1} listesi {0} listesiyle değiştirilecek (ekrana özel ayarlar dahil). Devam edilsin mi?",
                        "The playlist of {1} will be replaced by the one of {0} (including screen-specific settings). Continue?"),
 ("Editor_Duplicate", "Bu listede bir kez daha ekle", "Add once more to this playlist"),
 ("Editor_Remove", "Bu ekranın listesinden çıkar (kütüphanede kalır)", "Remove from this screen (stays in the library)"),
 ("Editor_RemoveSelected", "Seçilenleri bu ekrandan çıkar", "Remove selected from this screen"),
 ("Editor_RemovedOne", "\"{0}\", {1} listesinden çıkarıldı", "\"{0}\" removed from {1}"),
 ("Editor_RemovedMany", "{0} öğe {1} listesinden çıkarıldı", "{0} items removed from {1}"),
 ("Editor_EmptyTitle", "Bu ekranın listesi boş", "This screen's playlist is empty"),
 ("Editor_EmptyHint", "\"Kütüphaneden ekle\" ile medya seçin, dosya ekleyin ya da başka bir ekranın listesini kopyalayın.",
                      "Pick media with \"Add from library\", add files, or copy another screen's playlist."),
 ("Editor_NoSelection", "Bu ekrana özel ayarlar için listeden bir öğe seçin.\nCtrl veya Shift ile birden fazla öğe seçebilirsiniz.",
                        "Select an item to set screen-specific values.\nUse Ctrl or Shift to select several."),
 ("Editor_BulkTitle", "Seçili öğeler (yalnızca bu ekran)", "Selected items (this screen only)"),
 ("Editor_BulkHint", "Değişiklikler yalnızca bu ekrandaki seçili öğelere uygulanır.", "Changes apply only to the selected items on this screen."),
 ("Editor_SettingsInfo", "Boş bırakılan / işaretlenmeyen ayarlar Genel sekmesindeki değerleri kullanır.", "Settings left unchecked use the values from the General tab."),
 ("Editor_Identity", "Ekran", "Screen"),
 ("Editor_OwnDuration", "Bu ekrana özel varsayılan resim süresi", "Own default image duration"),
 ("Editor_GeneralValue", "Genel ayar: {0}", "General setting: {0}"),
 ("Editor_OwnTransitionDuration", "Bu ekrana özel geçiş süresi", "Own transition duration"),
 ("Editor_OwnVolume", "Bu ekrana özel ses seviyesi", "Own volume"),
 ("Editor_AudioOtherScreen", "Ses şu an yalnızca Ekran {0}'dan çıkacak şekilde ayarlı (Ekranlar sekmesi, sol alt).", "Sound is set to play only from screen {0} (Screens tab, bottom left)."),
 ("Editor_AudioThisScreen", "Video sesi yalnızca bu ekrandan çıkar.", "Video sound plays only from this screen."),
 ("Editor_OwnHours", "Bu ekrana özel çalışma saatleri", "Own opening hours"),
 ("Editor_OwnHoursHint", "Örneğin vitrin ekranı gece kapanırken içerideki ekran açık kalabilir.", "E.g. the window display can switch off at night while the indoor one stays on."),
 ("Entry_ScreenSpecific", "bu ekrana özel", "screen-specific"),
 ("Entry_OverrideInfo", "Buradaki değerler yalnızca bu ekranda geçerlidir. Değiştirmediğiniz değerler kütüphanedeki varsayılanlardan gelir.",
                        "Values here apply to this screen only. Anything you don't change comes from the library defaults."),
 ("Entry_ActiveHere", "Bu ekranda aktif", "Active on this screen"),
 ("Entry_ActiveTooltip", "Bu ekranda aktif", "Active on this screen"),
 ("Entry_DurationHere", "Bu ekrandaki süre (sn)", "Duration on this screen (s)"),
 ("Entry_TransitionHere", "Bu öğeye geçiş", "Transition into this item"),
 ("Entry_TransitionScreen", "Ekranın ayarı", "Screen setting"),
 ("Entry_OwnDates", "Bu ekrana özel tarih aralığı", "Own date range on this screen"),
 ("Entry_OwnSchedule", "Bu ekrana özel gün ve saat planı", "Own days and hours on this screen"),
 ("Entry_DefaultFromLibrary", "Varsayılan (kütüphane): {0}", "Default (library): {0}"),
 ("Entry_DefaultFromScreen", "Varsayılan (ekran): {0}", "Default (screen): {0}"),
 ("Entry_Active", "aktif", "active"),
 ("Entry_Inactive", "pasif", "inactive"),
 ("Entry_Reset", "Varsayılana döndür", "Reset to default"),
 ("Entry_ResetAll", "Tümünü varsayılana döndür", "Reset all to default"),
 ("Duplicate_Title_Exact", "Bu dosya kütüphanede zaten var", "This file is already in the library"),
 ("Duplicate_Title_SimilarImage", "Görsel olarak aynı bir resim kütüphanede var", "A visually identical picture is already in the library"),
 ("Duplicate_Title_SimilarVideo", "Muhtemelen aynı video kütüphanede var", "Probably the same video is already in the library"),
 ("Duplicate_Title_SameName", "Aynı isimde, içeriği farklı bir dosya var", "A different file with the same name exists"),
 ("Duplicate_Explain_Exact", "İçerikleri birebir aynı (dosya adı farklı olsa bile). Mevcut olanı kullanırsanız diskte yer kaplamaz; tekrar eklemek {0} daha yer tutar.",
                             "The contents are identical (even if the names differ). Using the existing one takes no extra space; adding again uses {0} more."),
 ("Duplicate_Explain_SimilarImage", "Resimler görsel olarak aynı görünüyor (yeniden kaydedilmiş, küçültülmüş veya farklı formatta olabilir).",
                                    "The pictures look the same (maybe re-saved, resized or in another format)."),
 ("Duplicate_Explain_SimilarVideo", "Süre, çözünürlük ve boyut neredeyse aynı; büyük ihtimalle aynı videonun başka bir kopyası.",
                                    "Length, resolution and size are nearly the same – most likely another copy of the same video."),
 ("Duplicate_Explain_SameName", "Muhtemelen güncellenmiş bir sürüm. \"Eskisinin yerine koy\" derseniz ekranlardaki yeri ve ayarları korunur, eski dosya silinir.",
                                "Probably an updated version. \"Replace\" keeps its place and settings on every screen and deletes the old file."),
 ("Duplicate_New", "Eklemek istediğiniz", "File to add"),
 ("Duplicate_Existing", "Kütüphanede olan", "Already in the library"),
 ("Duplicate_UseExisting", "Mevcut olanı kullan", "Use the existing one"),
 ("Duplicate_AddCopy", "Yine de ayrı ekle (+{0})", "Add anyway (+{0})"),
 ("Duplicate_Replace", "Eskisinin yerine koy", "Replace the old one"),
 ("Duplicate_Skip", "Atla", "Skip"),
 ("Duplicate_ApplyToAll", "Bu içe aktarmadaki benzer durumlar için de aynısını yap", "Do the same for similar cases in this import"),
 # ---- v1.3 updates / license ----
 ("Update_Section", "Güncellemeler", "Updates"),
 ("Update_CheckNow", "Güncellemeleri kontrol et", "Check for updates"),
 ("Update_InstallNow", "Şimdi güncelle", "Update now"),
 ("Update_ReleaseNotes", "Sürüm notları", "Release notes"),
 ("Update_AutoCheck", "Güncellemeleri otomatik kontrol et (günde bir kez)", "Check for updates automatically (once a day)"),
 ("Update_AutoInstall", "Güncellemeyi sessiz bir anda kendiliğinden kur", "Install updates by itself at a quiet time"),
 ("Update_Hint", "Sessiz an: çalışma saatleri dışı, gösterim kapalıyken veya gece 03:00–05:00. Yeni sürüm sorun çıkarırsa önceki sürüme kendiliğinden geri dönülür.",
                 "Quiet time: outside opening hours, while playback is stopped or at night 03:00–05:00. If a new version misbehaves, the previous one is restored automatically."),
 ("Update_Checking", "Güncellemeler kontrol ediliyor…", "Checking for updates…"),
 ("Update_Downloading", "Sürüm {0} indiriliyor…", "Downloading version {0}…"),
 ("Update_Ready", "Sürüm {0} indirildi ve doğrulandı. Kurmak için \"Şimdi güncelle\".", "Version {0} downloaded and verified. Click \"Update now\" to install."),
 ("Update_ReadyAuto", "Sürüm {0} indirildi; ilk sessiz anda kendiliğinden kurulacak (isterseniz şimdi kurabilirsiniz).",
                      "Version {0} is downloaded and will install itself at the next quiet time (or install it now)."),
 ("Update_ReadyAsk", "Yeni sürüm {0} hazır. Ayarlar → Genel → Güncellemeler.", "New version {0} is ready. Settings → General → Updates."),
 ("Update_UpToDate", "Güncel (sürüm {0})", "Up to date (version {0})"),
 ("Update_Failed", "Güncelleme kontrolü başarısız: {0}", "Update check failed: {0}"),
 ("Update_NoNetwork", "internet bağlantısı yok", "no internet connection"),
 ("Update_LastCheck", "son kontrol {0}", "last checked {0}"),
 ("Update_NeverChecked", "Henüz kontrol edilmedi", "Not checked yet"),
 ("Update_InstallConfirm", "Sürüm {0} kurulsun mu? Gösterim birkaç saniye duracak, ayarlar ve medya korunur.",
                           "Install version {0}? Playback pauses for a few seconds; settings and media are kept."),
 ("Update_Done", "Kodiz Signage {0} sürümüne güncellendi.", "Kodiz Signage was updated to version {0}."),
 ("License_Line", "Lisans: {0} – ticari kullanım izne tabidir", "License: {0} – commercial use requires permission"),
 ("License_View", "Lisansı görüntüle", "View license"),
 ("License_Notices", "Üçüncü taraf bildirimleri", "Third-party notices"),
 ("License_Source", "Kaynak kodu", "Source code"),
 ("General_InvalidColor", "Geçersiz renk. #RRGGBB biçiminde girin.", "Invalid color. Use #RRGGBB."),
 # ---- v1.4 ----
 ("Media_OfficeMissing", "Sunumlar dönüştürülemedi (PowerPoint veya LibreOffice kurulu değil). Sunumu PDF olarak kaydedip ekleyebilirsiniz:\n{0}",
                         "Presentations could not be converted (PowerPoint or LibreOffice is not installed). Save them as PDF and add the PDF instead:\n{0}"),
 ("Transition_Slide", "Kaydırma", "Slide"),
 ("Transition_Zoom", "Yakınlaşma", "Zoom"),
 ("Motion_Title", "Resim hareketi", "Image motion"),
 ("Motion_None", "Sabit", "Still"),
 ("Motion_KenBurns", "Ken Burns (yavaş yakınlaşma ve kaydırma)", "Ken Burns (slow zoom and pan)"),
 ("Motion_Hint", "Resimler gösterilirken hafifçe yakınlaşır ve kayar; sabit ekranlarda canlılık katar.", "Images slowly zoom and pan while shown, bringing still screens to life."),
 ("Slide_WindowTitle", "Slayt", "Slide"),
 ("Slide_CreateButton", "Slayt oluştur", "Create slide"),
 ("Slide_CreateHint", "Duyuru, fiyat listesi veya QR kod slaytı hazırlayın – dosya gerekmez", "Make an announcement, price list or QR code slide – no file needed"),
 ("Slide_EditButton", "Slaytı düzenle", "Edit slide"),
 ("Slide_Create", "Kütüphaneye ekle", "Add to library"),
 ("Slide_Update", "Değişiklikleri kaydet", "Save changes"),
 ("Slide_SaveHint", "Slayt bir resim olarak kaydedilir; ekranlarda diğer medya gibi oynatılır.", "The slide is saved as an image and plays like any other media."),
 ("Slide_Template", "Şablon", "Template"),
 ("Slide_TemplateAnnouncement", "Duyuru", "Announcement"),
 ("Slide_TemplatePriceList", "Fiyat listesi / menü", "Price list / menu"),
 ("Slide_TemplateQr", "QR kod", "QR code"),
 ("Slide_Title", "Başlık", "Title"),
 ("Slide_Subtitle", "Üst başlık / etiket", "Subtitle / label"),
 ("Slide_Body", "Metin", "Text"),
 ("Slide_Rows", "Satırlar", "Rows"),
 ("Slide_RowName", "Ürün", "Item"),
 ("Slide_RowPrice", "Fiyat", "Price"),
 ("Slide_RowNote", "Açıklama (isteğe bağlı)", "Description (optional)"),
 ("Slide_AddRow", "Satır ekle", "Add row"),
 ("Slide_QrContent", "QR içeriği", "QR content"),
 ("Slide_QrLink", "Bağlantı (web sitesi, menü, Instagram…)", "Link (website, menu, Instagram…)"),
 ("Slide_QrText", "Serbest metin", "Plain text"),
 ("Slide_QrWifi", "Wi-Fi ağı", "Wi-Fi network"),
 ("Slide_QrTextHint", "Ör. https://ornek.com", "e.g. https://example.com"),
 ("Slide_WifiName", "Ağ adı (SSID)", "Network name (SSID)"),
 ("Slide_WifiPassword", "Şifre", "Password"),
 ("Slide_Theme", "Tema", "Theme"),
 ("Slide_Background", "Arka plan", "Background"),
 ("Slide_Gradient", "Geçişli (2. renk)", "Gradient (2nd color)"),
 ("Slide_TextColor", "Yazı rengi", "Text color"),
 ("Slide_AccentColor", "Vurgu rengi", "Accent color"),
 ("Slide_Portrait", "Dikey ekran için (1080 × 1920)", "For portrait screens (1080 × 1920)"),
 ("Slide_TextSize", "Yazı boyutu", "Text size"),
 ("Slide_DefaultTitle", "Hoş geldiniz", "Welcome"),
 ("Slide_DefaultBody", "Bugün tüm sıcak içeceklerde %20 indirim", "20% off all hot drinks today"),
 ("Slide_DefaultRow1", "Çay", "Tea"),
 ("Slide_DefaultRow2", "Türk kahvesi", "Turkish coffee"),
 ("Theme_Night", "Gece", "Night"),
 ("Theme_Coffee", "Kahve", "Coffee"),
 ("Theme_Fresh", "Taze", "Fresh"),
 ("Theme_Berry", "Böğürtlen", "Berry"),
 ("Theme_Ocean", "Okyanus", "Ocean"),
 ("Theme_Paper", "Kağıt", "Paper"),
 ("Theme_Black", "Siyah", "Black"),
 ("Overlay_Tab", "Ekran üstü", "On screen"),
 ("Overlay_Info", "Saat, kayan yazı ve logo bu ekranda tüm içeriklerin üzerinde sürekli görünür.", "The clock, ticker and logo stay on top of all content on this screen."),
 ("Overlay_Clock", "Saat ve tarih", "Clock and date"),
 ("Overlay_ClockEnabled", "Saati göster", "Show the clock"),
 ("Overlay_ClockDate", "Tarihi de göster", "Also show the date"),
 ("Overlay_ClockSeconds", "Saniyeleri göster", "Show seconds"),
 ("Overlay_Position", "Konum", "Position"),
 ("Overlay_TopLeft", "Sol üst", "Top left"),
 ("Overlay_TopRight", "Sağ üst", "Top right"),
 ("Overlay_BottomLeft", "Sol alt", "Bottom left"),
 ("Overlay_BottomRight", "Sağ alt", "Bottom right"),
 ("Overlay_Bottom", "Altta", "Bottom"),
 ("Overlay_Top", "Üstte", "Top"),
 ("Overlay_Ticker", "Kayan yazı", "Ticker"),
 ("Overlay_TickerEnabled", "Kayan yazıyı göster", "Show the ticker"),
 ("Overlay_TickerText", "Metin", "Text"),
 ("Overlay_TickerSpeed", "Hız", "Speed"),
 ("Overlay_TickerBackground", "Şerit rengi", "Bar color"),
 ("Overlay_TickerTextColor", "Yazı rengi", "Text color"),
 ("Overlay_Logo", "Logo", "Logo"),
 ("Overlay_LogoHint", "Kütüphanedeki bir resmi seçin (şeffaf PNG en iyi sonucu verir).", "Pick an image from the library (a transparent PNG looks best)."),
 ("Overlay_NoLogo", "Logo yok", "No logo"),
 ("Overlay_LogoMissing", "(silinmiş medya)", "(deleted media)"),
 ("Overlay_LogoSize", "Genişlik (ekranın)", "Width (of the screen)"),
 ("Overlay_LogoOpacity", "Görünürlük", "Opacity"),
 ("Tray_Screens", "Ekranlar", "Screens"),
 ("Tray_ScreenEnabled", "Bu ekranda göster", "Show on this screen"),
 ("Tray_ScreenPreview", "Önizleme penceresi", "Preview window"),
 ("Tray_ScreenOff", "Kapalı", "Off"),
 ("Tray_ScreenFallback", "Ekranı bulunamadı – ana ekranda", "Display missing – on the primary display"),
 ("Transition_SlideUp", "Yukarı kaydırma", "Slide up"),
 ("Transition_FadeThroughBackground", "Arka plana karartarak", "Fade through background"),
 ("Transition_Wipe", "Silme (soldan sağa)", "Wipe (left to right)"),
 ("Transition_Circle", "Daire (ortadan açılma)", "Circle (opens from the center)"),
 ("Transition_Blur", "Bulanıklaşarak", "Blur"),
 ("Library_FilterAll", "Tüm medya", "All media"),
 ("Library_FilterImages", "Resimler", "Images"),
 ("Library_FilterVideos", "Videolar", "Videos"),
 ("Library_FilterSlides", "Slaytlar", "Slides"),
 ("Library_FilterUnused", "Hiçbir ekranda yok", "On no screen"),
 ("Library_FilterWarnings", "Uyarısı olanlar", "With warnings"),
 ("Library_FilterNotPlaying", "Şu an oynamayanlar", "Not playing now"),
 ("Library_FilterTooltip", "Listeyi daralt", "Narrow the list"),
 ("Library_SortOrder", "Kütüphane sırası", "Library order"),
 ("Library_SortName", "Ada göre", "By name"),
 ("Library_SortNewest", "En yeni eklenen", "Newest first"),
 ("Library_SortLargest", "En büyük dosya", "Largest file"),
 ("Library_SortTooltip", "Sıralama (sürükleyerek sıralama yalnızca kütüphane sırasında)", "Sort (drag to reorder only in library order)"),
 ("Stats_Section", "Gösterim istatistikleri", "Play statistics"),
 ("Stats_Description", "Her medyanın hangi ekranda kaç kez ve ne kadar süre gösterildiği günlük olarak kaydedilir (son 90 gün). Reklam ve kampanya raporları için CSV olarak dışa aktarabilirsiniz.",
                       "How often and how long each media was shown on each screen is recorded per day (last 90 days). Export it as CSV for ad and campaign reports."),
 ("Stats_Export", "CSV olarak dışa aktar", "Export as CSV"),
 ("Stats_Reset", "İstatistikleri sıfırla", "Reset statistics"),
 ("Stats_ResetConfirm", "Tüm gösterim istatistikleri silinsin mi?", "Delete all play statistics?"),
 ("Stats_Exported", "İstatistikler kaydedildi:\n{0}", "Statistics saved:\n{0}"),
 ("Stats_ExportFailed", "İstatistikler kaydedilemedi: {0}", "Statistics could not be saved: {0}"),
 ("Stats_FileType", "CSV dosyası (Excel)", "CSV file (Excel)"),
 ("Stats_ColDate", "Tarih", "Date"),
 ("Stats_ColScreen", "Ekran", "Screen"),
 ("Stats_ColMedia", "Medya", "Media"),
 ("Stats_ColPlays", "Gösterim sayısı", "Plays"),
 ("Stats_ColSeconds", "Toplam saniye", "Total seconds"),
 ("Stats_ColTime", "Toplam süre", "Total time"),
 ("Stats_None", "Son 30 günde gösterilmedi", "Not shown in the last 30 days"),
 ("Stats_Summary", "Bugün {0} · 7 gün: {1} gösterim ({2}) · 30 gün: {3} ({4})", "Today {0} · 7 days: {1} plays ({2}) · 30 days: {3} ({4})"),
 ("Stats_Hours", "{0} sa {1} dk", "{0} h {1} min"),
 ("Stats_Minutes", "{0} dk", "{0} min"),
 ("Stats_Seconds", "{0} sn", "{0} s"),
 ("Stats_DetailsTooltip", "Tüm ekranlardaki gösterimler (ayrıntı için Genel › Gösterim istatistikleri › CSV)", "Plays on all screens (details: General › Play statistics › CSV)"),
 ("Color_Open", "Palet ve renk seçici", "Palette and color picker"),
 ("Color_HexHint", "HEX renk kodu, ör. #1E1B4B (başındaki # olmadan da yazılabilir)", "HEX color code, e.g. #1E1B4B (the leading # is optional)"),
 ("Color_Palette", "Palet", "Palette"),
 ("Color_Custom", "Özel renk", "Custom color"),
 ("Color_Hue", "Renk tonu", "Hue"),
 ("Color_Revert", "Önceki renge dön", "Back to the previous color"),
 ("Color_Done", "Tamam", "Done"),
 ("Web_Section", "Telefondan yönetim", "Phone control"),
 ("Web_Description", "Aynı Wi-Fi ağındaki telefon veya tabletten gösterimi başlatıp durdurun, ekranları açıp kapatın, medya yükleyin. İnternet gerekmez; yalnızca yerel ağda çalışır.",
                     "Start or stop playback, switch screens and upload media from a phone or tablet on the same Wi-Fi. No internet needed; works only on the local network."),
 ("Web_Pin", "Telefon PIN'i (4–12 rakam)", "Phone PIN (4–12 digits)"),
 ("Web_SavePin", "PIN'i kaydet", "Save PIN"),
 ("Web_PinSet", "PIN ayarlı. Değiştirince tüm telefonların oturumu kapanır.", "PIN set. Changing it signs every phone out."),
 ("Web_PinNotSet", "Önce bir PIN belirleyin.", "Set a PIN first."),
 ("Web_PinSaved", "Telefon PIN'i kaydedildi.", "Phone PIN saved."),
 ("Web_Enabled", "Telefondan yönetimi aç", "Enable phone control"),
 ("Web_Port", "Port", "Port"),
 ("Web_Running", "Açık – telefonda bu adreslerden birini açın veya QR kodu okutun:", "On – open one of these addresses on the phone or scan the QR code:"),
 ("Web_NoNetwork", "Açık, ancak bilgisayar bir ağa bağlı değil.", "On, but this PC is not connected to a network."),
 ("Web_NeedPin", "Telefondan yönetimi açmak için önce bir telefon PIN'i belirleyin.", "Set a phone PIN before enabling phone control."),
 ("Web_Off", "Kapalı", "Off"),
 ("Web_PortInUse", "Port {0} başka bir uygulama tarafından kullanılıyor. Farklı bir port girin.", "Port {0} is used by another app. Enter a different port."),
 ("Web_CopyUrl", "Adresi kopyala", "Copy address"),
 ("Web_QrHint", "Telefon kamerasıyla okutun", "Scan with the phone camera"),
 ("Web_FirewallNote", "İlk açılışta Windows Güvenlik Duvarı izin isteyebilir: \"Özel ağlar\" için izin verin. Herkese açık ağlarda (kafe, otel) açmayın.",
                      "On first use Windows Firewall may ask for permission: allow \"Private networks\". Don't enable it on public networks (cafés, hotels)."),
 ("Web_TypeImage", "Resim", "Image"),
 ("Web_TypeVideo", "Video", "Video"),
 ("Web_TypeSlide", "Slayt", "Slide"),
 ("Web_Uploaded", "Eklendi: {0}", "Added: {0}"),
 ("Web_AlreadyInLibrary", "Zaten kütüphanede: {0}", "Already in the library: {0}"),
 ("Web_Unsupported", "Desteklenmeyen dosya: {0}", "Unsupported file: {0}"),
 ("Web_UploadFailed", "Eklenemedi: {0}", "Could not add: {0}"),
 ("Wizard_Welcome", "Kodiz Signage'a hoş geldiniz", "Welcome to Kodiz Signage"),
 ("Wizard_WelcomeText", "Birkaç adımda ekranlarınızı hazırlayalım. Her şeyi daha sonra Ayarlar'dan değiştirebilirsiniz.", "Let's set up your screens in a few steps. You can change everything later in Settings."),
 ("Wizard_Language", "Dil / Language", "Dil / Language"),
 ("Wizard_ScreensTitle", "Ekranlar", "Screens"),
 ("Wizard_ScreensOne", "Bir ekran bulundu. Gösterim bu ekranda tam ekran oynatılacak.", "One display found. The show plays full screen on it."),
 ("Wizard_ScreensMany", "{0} ekran bulundu. Hangilerinde gösterim yapılsın?", "{0} displays found. Which ones should show content?"),
 ("Wizard_Primary", "ana ekran", "primary"),
 ("Wizard_SameContent", "Tüm ekranlarda aynı içerik (her ekran için ayrı liste daha sonra ayarlanabilir)", "Same content on all screens (separate lists per screen can be set later)"),
 ("Wizard_ScreensLater", "Yeni bir TV takarsanız Ayarlar › Ekranlar bölümünden ekleyebilirsiniz.", "If you connect another TV later, add it under Settings › Screens."),
 ("Wizard_ContentTitle", "İçerik ve başlangıç", "Content and startup"),
 ("Wizard_ContentText", "Resim, video, PDF veya sunum ekleyin ya da hazır şablonlarla bir slayt oluşturun.", "Add images, videos, PDFs or presentations, or create a slide from a template."),
 ("Wizard_MediaCount", "Kütüphanede {0} medya var.", "{0} media in the library."),
 ("Wizard_Autostart", "Windows açılınca otomatik başlat", "Start automatically with Windows"),
 ("Wizard_Autoplay", "Açılınca gösterimi hemen başlat", "Start playback right away when opened"),
 ("Wizard_Shortcut", "Gösterim sırasında ayarları açmak için sistem tepsisindeki simgeye çift tıklayın veya kısayolu kullanın.", "During playback, double-click the tray icon or use the shortcut to open the settings."),
 ("Wizard_Skip", "Atla", "Skip"),
 ("Wizard_Back", "Geri", "Back"),
 ("Wizard_Next", "İleri", "Next"),
 ("Wizard_Finish", "Bitir", "Finish"),
 ("Update_RateLimit", "GitHub bu ağdan gelen istekleri geçici olarak sınırladı; bir saat içinde kendiliğinden düzelir",
                      "GitHub is temporarily limiting requests from this network; it clears by itself within an hour"),
 ("Update_NotFound", "güncelleme dosyası henüz yayında değil, biraz sonra tekrar deneyin", "the update file is not published yet, try again shortly"),
 ("AppTheme_Title", "Tema", "Theme"),
 ("AppTheme_System", "Windows ile aynı", "Same as Windows"),
 ("AppTheme_Light", "Aydınlık", "Light"),
 ("AppTheme_Dark", "Koyu", "Dark"),
 ("Touch_LongPress", "Ekrana 2 saniye basılı tutunca ayarlar açılsın", "Hold the screen for 2 seconds to open the settings"),
 ("Touch_LongPressHint", "Dokunmatik ekranlarda klavye ve görev çubuğu olmadan ayarlara ulaşmak için. PIN varsa sorulur.",
                         "For touch screens without a keyboard or taskbar. The PIN is asked if one is set."),
]
def write(path, idx, lang):
    keys=set()
    out=['<!-- Generated by strings.py – edit that file, not this one. -->',
         '<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"',
         '                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"',
         '                    xmlns:sys="clr-namespace:System;assembly=mscorlib">']
    for row in S:
        assert row[0] not in keys, row[0]; keys.add(row[0])
        val=escape(row[idx], {'"':'&quot;'}).replace('\n','&#10;')
        out.append(f'    <sys:String x:Key="{row[0]}" xml:space="preserve">{val}</sys:String>')
    out.append('</ResourceDictionary>\n')
    open(path,'w',encoding='utf-8').write('\n'.join(out))
import os
d=os.path.dirname(os.path.abspath(__file__))
write(os.path.join(d,'Strings.tr.xaml'),1,'tr')
write(os.path.join(d,'Strings.en.xaml'),2,'en')
